name: vashoz
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  cached_network_image: ^3.4.1
  collection: ^1.18.0
  either_dart: ^1.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.6
  flutter_native_splash: ^2.4.1
  flutter_screenutil: ^5.9.3
  get_it: ^7.7.0
  go_router: ^14.2.7
  google_fonts: ^6.2.1
  http: ^1.2.2
  hydrated_bloc: ^9.1.5
  image_picker: ^1.1.2
  in_app_update: ^4.2.3
  internet_connection_checker: 1.0.0+1
  intl: ^0.19.0
  package_info_plus: ^8.0.2
  path_provider: ^2.1.4
  url_launcher: ^6.3.0
  mason_cli: ^0.1.0-dev.56
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.1.0
  convex_bottom_bar: ^3.2.0
  carousel_slider: ^5.0.0
  smooth_page_indicator: 
  flutter_rating_bar: ^4.0.1
  timelines_plus: ^1.0.3
  expandable: ^5.0.1
  webview_flutter: ^4.0.0
  flutter_slidable:
    git:
      url: https://github.com/letsar/flutter_slidable.git
      ref: master
  dotted_border: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/mock/
    - assets/images/
